#pragma once
#include "元件伏安特性监控.h"
#include "基尔霍夫定律监控.h"
#include "叠加原理监控.h"
#include "戴维南定理监控.h"
#include "电压源与电流源的等效变换监控.h"
#include "一阶电路的响应测试监控.h"
#include "二阶动态电路响应的研究监控.h"
#include "VCVS实验监控.h"
#include "二端口网络的研究监控.h"
#include "最大功率传输条件的测定监控.h"
#include "电路状态轨迹的观测监控.h"
#include "RLC元件阻抗特性的测定监控.h"
#include "RLC串联谐振电路的研究监控.h"
#include "单相铁心变压器特性的测试监控.h"
#include "单相电度表实验监控.h"
#include "三相交流电路电压电流的测量监控.h"
#include "日光灯功率因数的提高监控.h"
#include "回转器监控.h"

#define BMPTEMP "bmptemp/"
#define MONITORTEMP "monitortemp/"